name: BembaSonico
favicon: null
layout_spectrum: 0
typography_spectrum: 0.597221658565104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#570000'
    - '#ff6a01'
    - '#af3000'
    - '#9f0000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
