name: BembaSonico
favicon: null
layout_spectrum: 0.25706
typography_spectrum: 0.597221658565104
title: Bemba Sonico
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73058871-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0908'
    - '#fffffd'
    - '#4b4843'
    - '#9b896f'
    - '#17849b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
